[project]
name = "nirjas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tree-sitter>=0.25.2",
    "tree-sitter-language-pack>=1.1.2",
    "tomli>=2.0; python_version < '3.11'",
]

[project.scripts]
download-parsers = "scripts.download_parsers:main"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.9.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I"]  # isort
ignore = ["E501"]
